[package]
name = "url-cleaner-site-client"
version = "0.12.0-beta"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
clap = { version = "4.5.54", features = ["derive"] }
futures-util = "0.3.31"
http-body-util = "0.1.3"
hyper = { version = "1.8.1", features = ["client", "http1"] }
hyper-tls = "0.6.0"
hyper-util = { version = "0.1.19", features = ["client-legacy", "http1"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["fs", "io-std", "macros", "rt-multi-thread", "time"] }
tokio-tungstenite = { version = "0.28.0", features = ["native-tls", "url"] }
tower-service = "0.3.3"
url = "2.5.8"

[lints]
workspace = true
