[package]
name = "url-cleaner-benchmarking"
version = "0.12.0-beta"
edition = "2024"
publish = false

[dependencies]
clap = { version = "4.5.52", features = ["derive"] }
num-format = "0.4.4"
serde_json = "1.0.145"

[lints]
workspace = true
