[package]
name = "urlc-tool"
version = "0.12.0-beta"
edition = "2024"
publish = false

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
libc = "0.2.178"
num-format = "0.4.4"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[features]
default = ["bench"]
bench = []

[lints]
workspace = true
