[package]
name = "urlc-tool"
version = "0.12.0-beta"
edition = "2024"
publish = false

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
libc = "0.2.178"
num-format = "0.4.4"
psl = "2.1.174"
regex = "1.12.2"
reqwest = { version = "0.12.28", features = ["blocking"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.146", features = ["preserve_order"] }
serde_with = "3.16.1"

[features]
default = ["bench"]
bench = []

[lints]
workspace = true
